language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - 1507@holbertonschool.com
      - sneyd3r@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "project deploy"
  on:
    branch: master
